name: Generate Calendar Image
on:
  schedule:
    - cron: '13 5 * * *'  # This actually runs at 5:13 AM UTC
    - cron: '17 15 * * *' # This actually runs at 3:17 PM UTC
    - cron: '34 10 * * *' # This actually runs at 3:17 PM UTC
  workflow_dispatch:    # Allows manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run render
        env:
          CALENDAR_URL: ${{ secrets.CALENDAR_URL }}
        run: python render.py
      - name: Commit and push image
        run: |
          git config --global user.name "CalendarBot"
          git config --global user.email "bot@github.com"
          git add calendar.png
          git commit -m "Update calendar image" || exit 0
          git push
